import { execFileSync } from 'child_process';
import { promises as fs } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, '..');

const packageJsonPath = join(rootDir, 'package.json');
const versionFilePath = join(rootDir, 'src', 'version.ts');

const packageJsonRaw = await fs.readFile(packageJsonPath, 'utf8');
const packageJson = JSON.parse(packageJsonRaw);
const baseVersion = packageJson.version;

if (typeof baseVersion !== 'string' || baseVersion.length === 0) {
  throw new Error('package.json version is missing or invalid');
}

const tagRef = process.env.GITHUB_REF_NAME || process.env.RELEASE_TAG || '';
const tagVersion = tagRef.replace(/^v/, '');
const versionBase = tagVersion.length > 0 ? tagVersion : baseVersion;

const fullSha = process.env.GITHUB_SHA || getGitSha();
const shortSha = fullSha ? fullSha.slice(0, 7) : 'unknown';

const version = `${versionBase}-${shortSha}`;
const contents = `// This file is generated by scripts/generate-version.mjs\nexport const VERSION = '${version}';\n`;

await fs.writeFile(versionFilePath, contents, 'utf8');

function getGitSha() {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch (error) {
    return '';
  }
}
