import { promises as fs } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, '..');

const packageJsonPath = join(rootDir, 'package.json');
const versionFilePath = join(rootDir, 'src', 'version.ts');

const packageJsonRaw = await fs.readFile(packageJsonPath, 'utf8');
const packageJson = JSON.parse(packageJsonRaw);
const baseVersion = packageJson.version;

if (typeof baseVersion !== 'string' || baseVersion.length === 0) {
  throw new Error('package.json version is missing or invalid');
}

const now = new Date();
const pad2 = value => String(value).padStart(2, '0');
const timestamp =
  String(now.getUTCFullYear()) +
  pad2(now.getUTCMonth() + 1) +
  pad2(now.getUTCDate()) +
  pad2(now.getUTCHours()) +
  pad2(now.getUTCMinutes());

const version = `${baseVersion}.${timestamp}`;
const contents = `// This file is generated by scripts/generate-version.mjs\nexport const VERSION = '${version}';\n`;

await fs.writeFile(versionFilePath, contents, 'utf8');
